name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: sudo apt install pngquant 
      - run: pip install git+https://${MKDOCS}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 
  MKDOCS: ${{ secrets.MKDOCS }}
